name: 'Deploy'

runs:
  using: "composite"
  steps:
      - name: Deploy
        run: |
          gcloud run deploy java-rest-service-example \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
