name: 'containerization'

runs:
  using: "composite"
  steps:
    - shell: bash
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ env.PROJECT_NAME }}/helloworld:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ env.PROJECT_NAME }}/helloworld:latest
